steps:
  # 1. Build imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/rag:$COMMIT_SHA'
      - -t
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/rag:latest'
      - .
    id: build

  # 2. Push a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '--all-tags'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/rag'
    id: push
    waitFor: ['build']

  # 3. Deploy Cloud Run Service (RAG API)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - minddash-rag
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/rag:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--project=$PROJECT_ID'
      - '--service-account=minddash-rag-sa@$PROJECT_ID.iam.gserviceaccount.com'
    id: deploy-service
    waitFor: ['push']


substitutions:
  _REGION: us-central1
  _REPO: minddash-repo

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
